### ISSUE TITLE
Refactor battle system to support abstract battle controller

### ISSUE THREAD

**Issue by mario-nowak** [untitled-monster-tamer/untitled-monster-tamer-public-issue-tracker#1]
# Tasks

- [x] Rename `OnlineBattles` singleton to `OnlineBattleManager`
- [ ] Remove `OnlineBattle`-ish classes from client game
- [ ] Refactor `Battle` scene to support abstract battle driver
- [ ] Create battle driver for wild encounter
- [ ] Create battle driver for online battle
