### ISSUE TITLE
Add catching monsters via discs

### ISSUE THREAD

**Issue by mario-nowak** [untitled-monster-tamer/untitled-monster-tamer-public-issue-tracker#59]
```[tasklist]
### Tasks
- [ ] https://github.com/untitled-monster-tamer/untitled-monster-tamer-public-issue-tracker/issues/60
- [ ] https://github.com/untitled-monster-tamer/untitled-monster-tamer-public-issue-tracker/issues/61
- [ ] https://github.com/untitled-monster-tamer/untitled-monster-tamer-public-issue-tracker/issues/62
```
